# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addproduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1079, 1103)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.addproductimg = QtWidgets.QLabel(self.centralwidget)
        self.addproductimg.setText("")
        self.addproductimg.setPixmap(QtGui.QPixmap("icons/addproduct.png"))
        self.addproductimg.setObjectName("addproductimg")
        self.topLayout.addWidget(self.addproductimg)
        self.imgtexttitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.imgtexttitle.setFont(font)
        self.imgtexttitle.setObjectName("imgtexttitle")
        self.topLayout.addWidget(self.imgtexttitle)
        self.mainLayout.addLayout(self.topLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameentry = QtWidgets.QLineEdit(self.centralwidget)
        self.nameentry.setObjectName("nameentry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameentry)
        self.manufacturerlabel = QtWidgets.QLabel(self.centralwidget)
        self.manufacturerlabel.setObjectName("manufacturerlabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.manufacturerlabel)
        self.manufacturerentry = QtWidgets.QLineEdit(self.centralwidget)
        self.manufacturerentry.setObjectName("manufacturerentry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.manufacturerentry)
        self.priceentry = QtWidgets.QLineEdit(self.centralwidget)
        self.priceentry.setObjectName("priceentry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.priceentry)
        self.quotaentry = QtWidgets.QLineEdit(self.centralwidget)
        self.quotaentry.setObjectName("quotaentry")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.quotaentry)
        self.pricelabel = QtWidgets.QLabel(self.centralwidget)
        self.pricelabel.setObjectName("pricelabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pricelabel)
        self.quotalabel = QtWidgets.QLabel(self.centralwidget)
        self.quotalabel.setObjectName("quotalabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.quotalabel)
        self.uploadlabel = QtWidgets.QLabel(self.centralwidget)
        self.uploadlabel.setObjectName("uploadlabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.uploadlabel)
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setObjectName("uploadButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.uploadButton)
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setObjectName("submitButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.submitButton)
        self._label = QtWidgets.QLabel(self.centralwidget)
        self._label.setText("")
        self._label.setObjectName("_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self._label)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("background1.jpg"))
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label)
        self.mainLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Products"))
        self.imgtexttitle.setText(_translate("MainWindow", "Add Product"))
        self.nameLabel.setText(_translate("MainWindow", "Name:"))
        self.nameentry.setPlaceholderText(_translate("MainWindow", "Enter name of product"))
        self.manufacturerlabel.setText(_translate("MainWindow", "Manufacturer:"))
        self.manufacturerentry.setPlaceholderText(_translate("MainWindow", "Enter name of manufacturer"))
        self.priceentry.setPlaceholderText(_translate("MainWindow", "Enter price of product"))
        self.quotaentry.setPlaceholderText(_translate("MainWindow", "Enter Quota of product"))
        self.pricelabel.setText(_translate("MainWindow", "Price:"))
        self.quotalabel.setText(_translate("MainWindow", "Quota:"))
        self.uploadlabel.setText(_translate("MainWindow", "Upload:"))
        self.uploadButton.setText(_translate("MainWindow", "Browse"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
